version: '3.8'

services:
  app:
    build:
      context: .
    image: fastapi-app
    container_name: fastapi-container
    ports:
      - "8000:8000"
    restart: unless-stopped

  db:    
    image: postgres:13.8-bullseye
    container_name: postgres-container
    hostname: postgresdb_fastapi
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres 
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
    volumes:
      - ./data/postgresqldb:/var/lib/postgresql/data
    restart: unless-stopped



